### ISSUE TITLE
Example :: Strategy example for Indicators like RSI or VWAP or combined

### ISSUE THREAD

**Issue by rahulmr** [peerchemist/finta#109]
First of all thanks for wonderful module.
Example of ma1 crossover is very basic and does not help much, could you please help by providing some example like RSI or RSI Divergence or VWAP

1. Like if RSI is over candle close crosses from below 40 to above 40 in a 5 min candle, buy signal must be triggered.
2. With above condition combined with VWAP like close of current 5 min candle is above VWAP of 5 min candle

Some good examples which can be easily extended.

Would also like to know how to code complex strategies or strategies having 4 or more indicators.
Below strategy for example:

1. Current day opens at price greater than previous day high.
2. Price crosses previous day high (above to below) and retest the previous day high again, create a sell trigger at this point and then first target is kept at previous day close and second target at previous day low.
3. Similarly when current day opens at price less and than previous day low.
4. Price crosses above previous day low and again retest the same , create a buy trigger and first target is previous day close and second target is previous day high 

How to code such strategies and find returns on it.

Thanks in advance for helping out.

**Comment by peerchemist** [comment]
Sorry such things are beyond the scope of the library. This is not algo trading library, just a collection of technical indicators which should help anyone to assemble their own trading program.
