### ISSUE TITLE
AttributeError: type object 'TA' has no attribute 'EVSTC'

### ISSUE THREAD

**Issue by ecojam** [peerchemist/finta#114]
AttributeError

output of the formula

AttributeError: type object 'TA' has no attribute 'EVSTC'

 
Using 1.3

**Comment by peerchemist** [comment]
How are you using it?

TA surely does have a method EVSTC.

```
n [1]: TA.EVSTC?                                                                                                                                                                                                                                                   
Signature:
TA.EVSTC(
    cls,
    ohlc: pandas.core.frame.DataFrame,
    period_fast: int = 12,
    period_slow: int = 30,
    k_period: int = 10,
    d_period: int = 3,
    adjust: bool = True,
) -> pandas.core.series.Series
Docstring: Modification of Schaff Trend Cycle using EVWMA MACD for calculation
File:      ~/projects/finta/finta/finta.py
Type:      function
```

**Comment by ecojam** [comment]
I'm only printing the output in my python code:

    stc = TA.EVSTC(ohlc)
    print(evstc)

James

**Comment by peerchemist** [comment]
You sure you run 1.3?

**Comment by ecojam** [comment]
Yes it's 1.3. I opened the file on my system and I can see the EVSTC code
is in the file. Using the below for any other indicator will generate an
output, but not EVSTC for some reason.

evstc = TA.EVSTC(ohlc)
print(evstc)

**Comment by peerchemist** [comment]
Maybe remove all local files and pull from pypi again?

**Comment by peerchemist** [comment]
We good?

**Comment by ecojam** [comment]
It's working now. Thank you sir. Excellent work!
