### ISSUE TITLE
error in example

### ISSUE THREAD

**Issue by bsdis** [peerchemist/finta#117]
`TA.BBANDS(ohlc, TA.KAMA(ohlc, 20))` gives error: `ValueError: window must be an integer`

A working example

A non working example

100% reliable

Run the example

pd:  1.2.4 (also tried 1.0.5) finta:  1.3 MacOS python 3.8.3

No

**Comment by bsdis** [comment]
change example to `TA.BBANDS(ohlc, MA = TA.KAMA(ohlc, 20))`

**Comment by peerchemist** [comment]
Thanks.
