### ISSUE TITLE
STOCH formula

### ISSUE THREAD

**Issue by PaschalisSk** [peerchemist/finta#20]
Hi,
shouldn't the formula for STOCH be `(ohlc['close'] - lowest_low) / (highest_high - lowest_low)`
instead of `(highest_high  - ohlc['close']) / (highest_high - lowest_low) ?`

And another question,
is there a reason we have `min_periods=period - 1` in SMA and some other indicators?
Seems weird to get the first average over period-1 instead of period (like the rest).
In addition, it seems inconsistent for SMA to produce one more row than WMA.

Thanks!

**Comment by peerchemist** [comment]
STOCH fixed in 6fee9cdce0b5b3271d43d249c519196d0394e75d

**Comment by peerchemist** [comment]
>  is there a reason we have `min_periods=period - 1` in SMA and some other indicators?

Just the decision I made in the early days of the project, it has it's reason but I am not so sure of it now.
