### ISSUE TITLE
RSI returned shape

### ISSUE THREAD

**Issue by PaschalisSk** [peerchemist/finta#21]
In RSI I don't thin we need `[1:]` in 
`delta = ohlc['close'].diff()[1:]`.
It causes the returned series to have one less row. If we just write
`delta = ohlc['close'].diff()` then it's the correct shape with nan in the, previously missing, first row.

**Comment by peerchemist** [comment]
Yes you are correct.

**Comment by peerchemist** [comment]
Fixed with https://github.com/peerchemist/finta/commit/faed2c09eca70a337bc175c8d7face2bca1f2256
