### ISSUE TITLE
STOCH period parameter in STOCHD

### ISSUE THREAD

**Issue by PaschalisSk** [peerchemist/finta#22]
I used `period=5` for calculating a STOCH column and when I created a STOCHD column I realised that the library uses the default `period=14` for calculating STOCH inside STOCHD which results in wrong calculations if we used a different period for STOCH e.g. `period=5`.

Could we have an additional parameter for STOCH's period in the STOCHD signature?
Alternatively, from a quick google search I realised the STOCHD always uses `period=3`, so maybe pass the period from STOCHD to STOCH and set the rolling window inside STOCHD to 3?

**Comment by peerchemist** [comment]
Fixed in 3c10b7e150f68db9bacee44df00e2a4fae09abcb
