### ISSUE TITLE
SSMA - smoothed simple moving average

### ISSUE THREAD

**Issue by rrfaria** [peerchemist/finta#26]
Hi, 

first of all thank you for your amazing job.

I would like to ask you if do you know how to calculate ssma?

I saw this indicator on iqoption site but I can't found how to calc this.

I found SMA but not SSMA

**Comment by peerchemist** [comment]
Hi,

I'm not familiar with the indicator. Is it maybe something like this: https://mahifx.com/mfxtrade/indicators/smoothed-moving-average-smma

**Comment by rrfaria** [comment]
check out this page it explain better then me

https://blog.iqoption.com/en/moving-average/

**Comment by peerchemist** [comment]
Unfortunately they do not explain what it is. I'll try to find something and see if I can reverse-engineer it.

**Comment by peerchemist** [comment]
I believe is what you have asked for: https://github.com/peerchemist/finta/commit/b191a588a6aab7193bbc622e1100c781183168c6
