### ISSUE TITLE
possible error in calculation

### ISSUE THREAD

**Issue by livinter** [peerchemist/finta#27]
may be you can double check.. 
but i think this line https://github.com/peerchemist/finta/blob/master/finta/finta.py#L798
should be         
ohlc["down_move"] = -ohlc["low"].diff()

**Comment by peerchemist** [comment]
I'll see to re-implement DMI.

**Comment by peerchemist** [comment]
Fixed with https://github.com/peerchemist/finta/commit/4929446dc652848149f62a14674c0e6433f05370

I still want to reimplement the entire DMI calculation though.
