### ISSUE TITLE
EMA calculation not matching with Tv output

### ISSUE THREAD

**Issue by mbmarx** [peerchemist/finta#31]
Hi
Can you please check EMA calculation the output is close but not matching with Tv outputs.
Better to test this with TV and realign the code.

**Comment by Dante2333** [comment]
It should not match because tradingview may use other libraries to create their indicators or modify the original formula to calculate their ema.

**Comment by peerchemist** [comment]
Resolved with: https://github.com/peerchemist/finta/pull/50

Use "adjust=False" to match TV.
