### ISSUE TITLE
PSAR indicator?

### ISSUE THREAD

**Issue by kanendosei** [peerchemist/finta#37]
PSAR is both valuable and often used by traders. Can we implement PSAR?

**Comment by peerchemist** [comment]
Sure.

**Comment by peerchemist** [comment]
Implemented with https://github.com/peerchemist/finta/commit/cb689b1c3fc4abaa8fa9cfd22d9da962ee877e47

Thanks @cyber-jack for the code.

**Comment by vishr** [comment]
@peerchemist Looks like PSAR is not in the current release, can we have a new release?

**Comment by peerchemist** [comment]
Yes, soon.
