### ISSUE TITLE
GPL

### ISSUE THREAD

**Issue by robertmartin8** [peerchemist/finta#4]
Hi, 

I'd just like to enquire as to why you decided to put this project under the GPL license, instead of something less restrictive.

Robert

**Comment by peerchemist** [comment]
I don't remember TBH. I was thinking of a switch to BSD-3, I may do that for the next version.

**Comment by robertmartin8** [comment]
The only reason I ask is that I was considering using `finta` in one of my projects, but the GPL makes it difficult, because I believe it forces any projects that use it to be open source and GPL. As this is a financial package, this seems like a bit of a barrier to adoption, because many people like to keep financial things proprietary.

This is just my two cents, and I respect your decisions as a developer (also I'm not a lawyer so I may have misinterpreted the terms of the GPL), but I think BSD-3 would suit this project much better.

**Comment by peerchemist** [comment]
Changed the licence to LGPL, I find that one most appealing at the moment.
