### ISSUE TITLE
Ichimoku Cloud

### ISSUE THREAD

**Issue by Dante2333** [peerchemist/finta#41]
I've read the code on the ichimoku cloud, would it be possible to make variables (9,26,52,26) to be malleable so we can do:

`TA.ichimoku(ohcl, 20,60,120,30) 
`
in an easy way rather than modifying the code from finta, if this can be done already, please let me know

Thanks!

**Comment by peerchemist** [comment]
Sure, I can have that done for the next release.

**Comment by peerchemist** [comment]
Resolved with https://github.com/peerchemist/finta/commit/ca31b51ed49dd653f3c3922473e87d083fa9666e
