### ISSUE TITLE
Using Numpy Arrays Instead of Pandas DataFrames

### ISSUE THREAD

**Issue by Sinansi** [peerchemist/finta#46]
Hello,

I am using finta library from Julia. I noticed I must pass price as Pandas DataFrame, and this adds extra function calls and overhead through PyCall. Is there a way I can use finta functions using Numpy Arrays instead of Pandas DataFrames? A lower level API maybe?!

Thank you!

**Comment by peerchemist** [comment]
Sorry I don't think that is possible.
However you can convert DataFrame to Numpy array: https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.to_numpy.html

**Comment by Sinansi** [comment]
Thank you!
