### ISSUE TITLE
Should return type in signature be DataFrame when returning pd.concat()?

### ISSUE THREAD

**Issue by BillEndow** [peerchemist/finta#48]
Great library, and I like your coding style.

In functions that return using the Pandas concat() function, the return type is currently specified as Pandas Series. Shouldn't it be DataFrame?

Example:
https://github.com/peerchemist/finta/blob/22460ba4a73272895ee162b0b8125988bbefe88c/finta/finta.py#L408

So shouldn't the signature:

https://github.com/peerchemist/finta/blob/22460ba4a73272895ee162b0b8125988bbefe88c/finta/finta.py#L376

instead be:

`...    ) -> DataFrame:`?

**Comment by peerchemist** [comment]
A good point.

**Comment by peerchemist** [comment]
Addressed in: https://github.com/peerchemist/finta/commit/dcfd3f33d85373bcbee2d75b97ddb5bd1b10b5ee
