### ISSUE TITLE
Williams Fractal indicator implementation

### ISSUE THREAD

**Issue by chromafunk** [peerchemist/finta#51]
https://learn.tradimo.com/technical-analysis-how-to-work-with-indicators/fractals-indicator

https://www.tradingview.com/script/Uyv9vQc2-Williams-Fractals-Tutorial-Template/

https://www.prorealcode.com/prorealtime-indicators/bill-williams-fractals/

This indicator is hot and widely used, I think it would be a very valuable addition to Finta. As plus, is not available in TA-lib or others. Note that I have edited the title because it's not FRAMA but, "Williams Fractal" which is different.

**Comment by phantomsamurai** [comment]
Can you please code a fractal feature its needed.

**Comment by peerchemist** [comment]
If I get some spare time I will. :)
