### ISSUE TITLE
ZLEMA not using any EMA

### ISSUE THREAD

**Issue by LucCADORET** [peerchemist/finta#53]
The ZLEMA function seems to only return the transformed data (before handling it to the ema method) but doesn't actually perform the EMA on the data.

The method code is:
```
       lag = (period - 1) / 2
        return pd.Series(
            (ohlc["close"] + (ohlc["close"].diff(lag))),
            name="{0} period ZLEMA.".format(period),
        )
```
Which doesn't include any EMA i.e. it is missing the last step in the ZLEMA pseudocode: https://en.wikipedia.org/wiki/Zero_lag_exponential_moving_average

**Comment by peerchemist** [comment]
You are right, resolved with https://github.com/peerchemist/finta/commit/eabc47ef8a9af81658299e8a02cf0b419a89b5b0
