### ISSUE TITLE
Add ichimoku cloud color green/red

### ISSUE THREAD

**Issue by Dante2333** [peerchemist/finta#54]
Please let me know if this would be possible:

        'cloud_green': df['senkou_span_a'] > df['senkou_span_b'],
        'cloud_red': df['senkou_span_b'] > df['senkou_span_a']

**Comment by peerchemist** [comment]
Sure, that is completely about your user-facing code though. Not sure how are you wrapping this up but as you demonstrate you can simply define a new series "cloud_green" which is made of true/false depending on whether or not df['senkou_span_a'] > df['senkou_span_b'].

It will be something like [True,  True, True, False, False, True, ...].

**Comment by Dante2333** [comment]
Yep, I though on that just after I posted but in the end would be a nice feature so non-tech-savy users can enjoy finta as well.

**Comment by peerchemist** [comment]
I cant implement that in finta as it's not in the scope of the library. That is on the frontend side.
