### ISSUE TITLE
help needed: how to pull indicator value from all time frame at one shot?

### ISSUE THREAD

**Issue by fxdt** [peerchemist/finta#56]
help wanted on how to pull an indicator value from all time-frame at one shot?

on TradingView, i pull out these values from an indicator

['GBPUSD', 'M: -53.00460785710888', 'W: -53.00460785710888', 'D: -18.48497324001634', 'H4: -7.875243664717016', 'H1: -33.94957983193184', 'M30: -32.47422680412316', 'M15: -22.485207100590525', 'M5: -31.232876712327133', 'M2: -41.45454545454205']
['GBPUSD']

let's take RSI as a sample, 
TA.RSI(ohlc).tail(10) will pull out for Daily and the past 10 days. i would like to see current data.

no idea how to get these info hence asking for help

pandas 1.03
python 3.7.6

**Comment by peerchemist** [comment]
You need last value?

TA.RSI(ohlc).values[-1]

**Comment by fxdt** [comment]
yes that is correct. 

TA.RSI(ohlc).values[-1] will default at which time interval ? How can i add more time interval   or it has to be individual and merge in a dataframe ?

**Comment by peerchemist** [comment]
TA.RSI defaults at 14 periods, to change it you can just pass second argument: TA.RSI(ohlc, 15).

**Comment by fxdt** [comment]
14 period is at daily timeframe. how about intraday timeframe?

**Comment by peerchemist** [comment]
FInta always does calculations on the dataset you give it to. If you gave it daily dataset you'll get daily dataset back, if you give it intraday dataset it will do math on the intraday data.

Give it intraday data as input.
