### ISSUE TITLE
Bug Vortex Indicator

### ISSUE THREAD

**Issue by Pcosmin** [peerchemist/finta#61]
The Vortex Indicator is not correctly implemented.

This should be the correct implementation based on this rules https://www.investopedia.com/terms/v/vortex-indicator-vi.asp : 
    
    VMP = pd.Series((ohlc["high"] - ohlc["low"].shift(1)).abs())
    VMM = pd.Series((ohlc["low"] - ohlc["high"].shift(1)).abs())

    VMPx = VMP.rolling(window=period).sum()
    VMMx = VMM.rolling(window=period).sum()
    TR = cls.TR(ohlc).rolling(window=period).sum()

    VIp = pd.Series(VMPx / TR, name="VIp").interpolate(method="index")
    VIm = pd.Series(VMMx / TR, name="VIm").interpolate(method="index")

    return pd.concat([VIm, VIp], axis=1)

**Comment by peerchemist** [comment]
Good spot, fixed.
