### ISSUE TITLE
Mobo breakout indicator

### ISSUE THREAD

**Issue by chandrab** [peerchemist/finta#62]
How implementing MOBO indicator (Momentum breakout)?
It's a derivative of the a Bollinger band but:
"MOBO bands are based on a zone of 0.80 standard deviation with a 10 period look-back"
If the price breaks out of the MOBO band it can signify a trend move or price spike
Explanation around 3:58 of video
https://www.youtube.com/watch?v=Y6q06t4mp2c

One thinkscript implementation that might help:

#Bollinger Bands MOBO(MOmentum BreakOut) [Thinkscript]
#============================================
#Explanation of how this works.  +/- 0.8 std deviation Bollinger Bands are the criteris for bullish/bearish plots. When the close rises above the upper band the signal is bullish and stays bullish until the ose moves below the lower band when the plot turns to bearish and remains bearish until the close rises above the upper band.
input MOBO_length = 10;#hint MOBO_length:The agg-bars used in the standard deviation(SD) calculation to define the upper and lower bands.
input Num_Dev_Dn = -0.8;#hint Num_Dev_Dn:The SD of the lower band. Similar to the 2,0 SD used in the Bollinger Bands
input Num_Dev_up =  0.8;#hint Num_Dev_up:The SD of the upper band. Similar to the 2,0 SD used in the Bollinger Bands

def sDev = StDev(data = c, length = MOBO_length);
def Midmobo = Average(c, length = MOBO_length);
def Lowermobo = Midmobo + Num_Dev_Dn * sDev;
def Uppermobo = Midmobo + Num_Dev_up * sDev;

**Comment by nathanielCherian** [comment]
MOBO seems very useful, I'm sure I will be using it soon. It is however just a BBAND with a different period and std. Only reason I see for keeping it in is simply for convenience. It is much easier to access indicator with ``` getattr(TA, MOBO)``` than have to pass in the different parameters manually. Also BBANDS previously only took an integer as a std value.

**Comment by peerchemist** [comment]
Implemented with ec511abae889b4c3dfe45b3be6be4309c12585d1, thanks @nathanielCherian
