### ISSUE TITLE
Implement regression tests

### ISSUE THREAD

**Issue by peerchemist** [peerchemist/finta#7]
Test against some older more polished code, for example ta-lib, and compare results to spot the regressions and bugs.
There is python wrapper here: https://github.com/mrjbq7/ta-lib

**Comment by bbeale** [comment]
I'd be willing to help with this. I think it might help me better understand some of the more obscure indicators.

**Comment by peerchemist** [comment]
There is initial work done on the `regtest` branch.

https://github.com/peerchemist/finta/blob/regtest/tests/test_reg.py
