### ISSUE TITLE
Why is the result different depending on the size of input dataframe?

### ISSUE THREAD

**Issue by sukwoo1414** [peerchemist/finta#71]
Thank you for the good library!
I want to ask a question that I am not sure if it is my fault or a library issue.

I calculated MACD with 100rows of 1 minute ohlcv historical data. 
First, I calculated it with whole 100 rows, and then I calculated it with last 80 rows.
And I saw that result of MACD and SIGNAL of same row (ex. index 99) of each calculation is different.

For example,

```
df = pd.read_csv("my_ohlcv.csv") #size of my_ohlcv is 100rows
result1 = TA.MACD(df)
df = df.iloc[-80:]
result2 = TA.MACD(df)

print(result1['MACD'].iloc[-1], result2['MACD']iloc[-1])

```
I expected result1.iloc[-1] and result2.iloc[-1] would be same, but the value was a little bit different.
But when I calculated CCI with same way I did with MACD, this problem doesn't happened and 2 results was totally identical. 
Why these things happens with MACD? Do I need bigger size of data for accurate MACD calculation? I also tested it with more than 200rows, but result was not identical either.

I'm using python3.6.9

**Comment by jomoho** [comment]
If you look at how MACD works you will see that it uses Exponential Weighted Moving Averages, using [pandas ewm](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.ewm.html). This means that basically, the whole history has an influence on the result. There is a proposal to add initialization to pandas ewm, which would be a basis for a workaround but currently, there is no solution for this problem available that I would be aware of.

CCI does not have this problem as it is using rolling windows and not ewm.

**Comment by peerchemist** [comment]
That is right, all historic data enters the calculation and will have effect on the result.
