### ISSUE TITLE
Relative Strength Index (RSI) calculation

### ISSUE THREAD

**Issue by charlyisidore** [peerchemist/finta#72]
First of all, many thanks for this nice python library. I am using the version 0.4.4.

I computed the RSI on data fetched using `ccxt`, and compared it with the RSI shown on cryptowat.ch.
Unfortunately, the RSI calculated by finta did not match the RSI calculated by cryptowat.ch.

After investigation, I realized that the way the exponential moving average (EMA) is calculated is different.

In finta, the EMA is computed with `alpha = 2 / (1 + period)` (i.e. the parameter `span` in https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.ewm.html )
In cryptowat.ch, the EMA seems computed with `alpha = 1 / period`.

As an example, I took the BTC/USDT symbol from binance.
https://cryptowat.ch/charts/BINANCE:BTC-USDT?period=1h

To test my assumption, I wrote a script for plotting different RSI values (requires ccxt, finta, mplfinance and pandas).

``` python
#!/usr/bin/env python3

import ccxt
from finta import TA
from datetime import datetime
import mplfinance as mpf
import pandas as pd

# https://cryptowat.ch/charts/BINANCE:BTC-USDT?period=1h
exchange_id = "binance"
symbol_id = "BTC/USDT"
timeframe = "1h"
period = 14


def fetch(exchange_id, symbol_id, timeframe):
    exchange = getattr(ccxt, exchange_id)()
    data = exchange.fetch_ohlcv(symbol_id, timeframe=timeframe)
    columns = ["date", "open", "high", "low", "close", "volume"]
    df = pd.DataFrame.from_records(data, index=["date"], columns=columns)
    df.index = pd.to_datetime(df.index, unit="ms")
    return df


def my_RSI(df, period):
    delta = df["close"].diff()
    up, down = delta.copy(), delta.copy()
    up[up < 0] = 0
    down[down > 0] = 0
    _gain = up.ewm(alpha=1.0 / period).mean()
    _loss = down.abs().ewm(alpha=1.0 / period).mean()
    rs = _gain / _loss
    return pd.Series(100.0 - (100.0 / (1.0 + rs)), name=f"{period} period RSI")


def plot(df):
    plots = [
        mpf.make_addplot(df["TA_RSI_1"], color="r", panel="lower"),
        mpf.make_addplot(df["TA_RSI_2"], color="g", panel="lower"),
        mpf.make_addplot(df["my_RSI"], color="b", panel="lower"),
    ]
    mpf.plot(df, type="candle", addplot=plots)


df = fetch(exchange_id, symbol_id, timeframe)
df["TA_RSI_1"] = TA.RSI(df, period)
df["TA_RSI_2"] = TA.RSI(df, 2 * period - 1)
df["my_RSI"] = my_RSI(df, period)

print(df.tail(20))
plot(df.tail(100))
```

The script above outputs the OHLC columns, plus:

- `TA_RSI_1`: the RSI calculated by finta with `span = period`.
- `TA_RSI_2`: the RSI calculated by finta with `span = 2 * period - 1` (should be equivalent to setting `alpha = 1/period`).
- `my_RSI`: the RSI calculated by my function `my_RSI` that computes the EMA with `alpha = 1/period`.

Here is the resulting table:

```
                        open     high      low    close       volume   TA_RSI_1   TA_RSI_2     my_RSI
date                                                                                                 
...
2020-07-11 20:00:00  9205.10  9217.24  9201.55  9216.86   635.630615  45.234820  46.166655  46.166655
2020-07-11 21:00:00  9216.86  9224.68  9207.74  9220.21   436.291969  47.639032  47.260102  47.260102
2020-07-11 22:00:00  9220.19  9236.11  9210.36  9218.41   835.240810  46.376785  46.711094  46.711094
2020-07-11 23:00:00  9218.42  9253.00  9218.02  9234.03   718.692534  57.620173  51.929694  51.929694
2020-07-12 00:00:00  9234.02  9268.52  9230.61  9250.99   994.539305  66.436767  56.868698  56.868698
2020-07-12 01:00:00  9250.99  9294.00  9243.48  9268.56  1859.797089  73.120963  61.304329  61.304329
2020-07-12 02:00:00  9268.56  9280.01  9260.09  9270.16   761.173114  73.671899  61.690696  61.690696
2020-07-12 03:00:00  9270.36  9284.15  9266.51  9272.47   858.523274  74.541190  62.276332  62.276332
2020-07-12 04:00:00  9272.47  9286.69  9261.22  9269.11   788.583932  70.627428  60.819928  60.819928
2020-07-12 05:00:00  9269.17  9277.21  9253.48  9264.84   344.009624  65.578534  58.933693  58.933693
```

The chart on cryptowat.ch shows the following:

![binance-btcusdt](https://user-images.githubusercontent.com/645647/87239906-e790c200-c446-11ea-95aa-27c507a40c7d.png)

The bottom panel contains the curve of the RSI as computed by cryptowat.ch.

The chart shown by my python script is the following:

![binance_finta](https://user-images.githubusercontent.com/645647/87239918-0db66200-c447-11ea-8306-72827748faa1.png)

The RSI is shown in the bottom panel.
The red curve is the RSI computed by finta (column `TA_RSI_1`), the blue curve is the RSI computed by `my_RSI`. We can see that the `TA_RSI_1` in red has some peaks far above 75, whereas `my_RSI` stays below 75 (sometimes reaches nearly 75), the latter matches strongly the behavior of the cryptowat.ch curve. So it supports the fact that cryptowat.ch uses `alpha = 1/period`.

I wonder if there is a standard "RSI". This website ( https://www.macroption.com/rsi-calculation/#wilders-smoothing-method ) states that the inventor of the RSI computed the EMA with `alpha = 1/period`, that seems to be the one adopted by cryptowat.ch.

Therefore, if it makes sense, my suggestion would be to replace these lines:

https://github.com/peerchemist/finta/blob/8642dd8c1fea66e5eb2e4c28af7e7de09dfdffef/finta/finta.py#L589-L591

by:

``` python
        # EMAs of ups and downs
        _gain = up.ewm(alpha=1.0/period, adjust=adjust).mean()
        _loss = down.abs().ewm(alpha=1.0/period, adjust=adjust).mean()
```

By the way, I think it would also be nice to add a parameter such as "column" to choose on which column of the dataframe the RSI is computed.

Many thanks.

**Comment by peerchemist** [comment]
```
   # EMAs of ups and downs
    _gain = up.ewm(alpha=1.0/period, adjust=adjust).mean()
    _loss = down.abs().ewm(alpha=1.0/period, adjust=adjust).mean()
```

Sounds reasonable, it also resolves regtest against TA_lib. But it breaks some other indicators, I must see how to handle this.
