### ISSUE TITLE
Inverse Fisher Transform applied on RSI

### ISSUE THREAD

**Issue by ecojam** [peerchemist/finta#75]
Regardless of the ohlc dataframe applied, the currently published code never generates negative values as expected. It should generate both positive and negative values in the output. Here are two other publicly available code implementations although they are not written in Python:

https://tr.tradingview.com/script/LxiuxNm4/
https://www.motivewave.com/studies/inverse_fisher_transform.htm

It may be possible that the recently closed "Relative Strength Index (RSI) calculation #72" has broken this indicator.

**Comment by peerchemist** [comment]
Please check with this commit: https://github.com/peerchemist/finta/commit/4ae429e98a5f40078d1e8b611d0ed17954a911b7

**Comment by peerchemist** [comment]
I'll close this, open a new ticket if you still find this broken.

**Comment by ecojam** [comment]
Thank you sir! Excellent work!

James
