### ISSUE TITLE
Error Calculating Ease Of movement

### ISSUE THREAD

**Issue by Physicworld** [peerchemist/finta#81]
Hey Man! this issue is very short!
There an error in the calculation of Ease of Movement
only replace for this:

distance = pd.Series(
			((data['high'] + data['low']) / 2) - ((data['high'].shift(1) + data['low'].shift(1)) / 2)
		)
#First error in postive sign!

box_ratio = pd.Series(
			(data['volume'] / 1000000.00) / (data['high'] - data['low'])
		)
# Second, like a good programming practice, you can use the .00 to say its a "floating" number.

Thanks a lot man! i'm doing a big trading bot with your library!

**Comment by peerchemist** [comment]
Solved with 18ad1c74dc7173275df78d36cbc2b227f9b2e4c1

**Comment by Physicworld** [comment]
distance = pd.Series(
((data['high'] + data['low']) / 2) - ((data['high'].shift(1) **+** data['low'].shift(1)) / 2)
)

Hey man! the error was on the sign :D!

**Comment by peerchemist** [comment]
Indeed. I'll get it fixed in a moment.
