### ISSUE TITLE
Accept dataframes with ohlc format irrespective of the case of column names

### ISSUE THREAD

**Issue by amartya-dev** [peerchemist/finta#83]
When I try to use the library with a dataframe I get from yfinance, it throws an error: KeyError: 'close'

Since the database contains a column named 'Close' instead of 'close', the library should be intelligent enough to accept that

Try running any function with the dataframe as specified above

Python: 3.6 pandas: 1.1.0

**Comment by peerchemist** [comment]
As it says in the readme:
```
Prepare data to use with finta:

finta expects properly formated ohlc DataFrame, with column names in lowercase: ["open", "high", "low", "close"] and ["volume"] for indicators that expect ohlcv input.

```

It is more work for me and the library to support upercase names of the column than for any user to normalize their data so it's understandable to the libary.
