### ISSUE TITLE
Schaff Trend Cycle indicator

### ISSUE THREAD

**Issue by satishchaudhary382** [peerchemist/finta#85]
While using STC method for calculating scahff trend cycle, the value does not range between 0 and 100 as the indicator should

I was expecting the value to be between 0 and 100

The indicator shows values greater than 100

**Comment by ftamimi** [comment]
Hello, do you know when we can expect a fix for the bug? Thanks

**Comment by peerchemist** [comment]
@ftamimi it seems it got fixed 19 days ago with this commit: https://github.com/peerchemist/finta/commit/cc3385be82b98d7b9444b880e736e4db7fae4843
