### ISSUE TITLE
RSI AND MACD NOT WORKING

### ISSUE THREAD

**Issue by mrtapo8** [peerchemist/finta#90]
RSI is not wokring, MACD too.

**Comment by mrtapo8** [comment]
`from finta import TA

import pandas as pd

ohlc = pd.read_csv("sviecky.csv")


print(ohlc)


print(TA.RSI(ohlc))`

my "sviecky.csv" looks like this
![image](https://user-images.githubusercontent.com/61843287/93132761-7daac800-f6d6-11ea-8828-354eaa0359ca.png)

**Comment by peerchemist** [comment]
Those timestamps look weird. How is RSI and MACD not working exactly? How does the output look?
