### ISSUE TITLE
Fisher indicator signal values

### ISSUE THREAD

**Issue by vishr** [peerchemist/finta#91]
As mentioned in the comment here https://github.com/peerchemist/finta/blob/dfadfa90c99bf0f8be9f0379e067ba4d74d923e0/finta/finta.py#L1769, I don't see signal values being returned.

Signal values to be returned along with fisher

No signal values

Always

Latest on macos, Python 3.8

**Comment by peerchemist** [comment]
Ok that comment is wrong, it's not in the scope of the indicator to return the signal line.
